name: 'Github Actions Nodemailer'
description: 'Github Actions to send email notifications using Nodemailer.'
author: 'Adel Kedjour <adel@kedjour.com>'
branding:
  icon: mail
  color: orange
inputs:
    host:
      description: SMTP server address
      required: true
    port:
      description: SMTP server port
      required: true
    secure:
      description: Whether this connection use TLS (default is true if smtp server port is 465)
      required: false      
    username:
      description: Authenticate as this user to SMTP server
      required: true
    password:
      description: Authenticate with this password to SMTP server
      required: true
    subject:
      description: Subject of mail message
      required: true
    to:
      description: Recipients mail addresses (separated with comma)
      required: true
    from:
      description: Full name of mail sender (might be with an email address specified in <>)
      required: true
    body:
      description: Body of mail message (might be a plain text or html)
      required: true
    cc:
      description: Carbon copy recipients (separated with comma)
      required: false
    bcc:
      description: Blind carbon copy recipients (separated with comma)
      required: false
    reply_to:
      description: An email address that will appear on the Reply-To field
      required: false
    
runs:
  using: 'docker'
  image: 'Dockerfile'
